### ISSUE TITLE
"Missing yield in generator while parsing" when parsing global generator functions

### ISSUE THREAD

**Issue by ComFreek** [browserify/browserify#1135]
Code to reproduce:

```
// test.js
global.test = function *() {}
```

Run `browserify test.js`.

Stack trace:

```
SyntaxError: Line 2: Missing yield in generator while parsing P:\test\test.js while parsing file: P:\test\test.js
    at Stream.end (C:\Users\ComFreek\AppData\Roaming\npm\node_modules\browserify\no
de_modules\insert-module-globals\index.js:73:21)
    at _end (C:\Users\ComFreek\AppData\Roaming\npm\node_modules\browserify\node_mod
ules\insert-module-globals\node_modules\through\index.js:65:9)
    at Stream.stream.end (C:\Users\ComFreek\AppData\Roaming\npm\node_modules\browse
rify\node_modules\insert-module-globals\node_modules\through\index.js:74:5)
    at Transform.onend (C:\Users\ComFreek\AppData\Roaming\npm\node_modules\browseri
fy\node_modules\module-deps\node_modules\through2\node_modules\readable-stream\l
ib\_stream_readable.js:523:10)
    at Transform.g (events.js:240:16)
    at emitNone (events.js:70:20)
    at Transform.emit (events.js:147:7)
    at C:\Users\ComFreek\AppData\Roaming\npm\node_modules\browserify\node_modules\m
odule-deps\node_modules\through2\node_modules\readable-stream\lib\_stream_readab
le.js:965:16
    at process._tickCallback (node.js:337:11)
PS P:\test>
```

**Note** that this seems to only happen when `global` is involved.
The following code does not lead to an error:

```
var a = function*(){}
```

https://github.com/substack/node-detective/issues/34
I could not find any official resources on this topic (whether a generator function without yield statements is valid) in a quick way, however, this [issue at node-detective](http://people.mozilla.org/~jorendorff/es6-draft.html#sec-generator-function-definitions) and V8 which allows such functions support the validity of such functions.

**Comment by DylanPiercey** [comment]
Having this problem as well...

**Comment by goto-bus-stop** [comment]
closing; https://github.com/browserify/detective/issues/34 is fixed
