### ISSUE TITLE
Error running browserify on centos AWS server

### ISSUE THREAD

**Issue by tnrich** [browserify/browserify#1368]
Hey there, I tried running this command:

```
$ browserify ./vede/browserifyModules.js -o ./vede/resources/js/browserifyBundle.js
```

on my local machine (OSX)
and everything is working fine. 

However, on a centos AWS server, I'm running into this error when I try to run the exact same command. Anyone have any experience with this sort of issue? Any help would be greatly appreciated!!

```
$ browserify ./vede/browserifyModules.js -o ./vede/resources/js/browserifyBundle.js
Error: Parsing file /home/teselagen/ve/vede/node_modules/jsondiffpatch/src/filters/texts.js: Object #<Object> has no method 'isIdentifierPart'
    at Deps.parseDeps (/usr/lib/node_modules/browserify/node_modules/module-deps/index.js:437:28)
    at fromSource (/usr/lib/node_modules/browserify/node_modules/module-deps/index.js:376:44)
    at /usr/lib/node_modules/browserify/node_modules/module-deps/index.js:370:17
    at ConcatStream.<anonymous> (/usr/lib/node_modules/browserify/node_modules/concat-stream/index.js:36:43)
    at ConcatStream.EventEmitter.emit (events.js:117:20)
    at finishMaybe (/usr/lib/node_modules/browserify/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:460:14)
    at endWritable (/usr/lib/node_modules/browserify/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:469:3)
    at ConcatStream.Writable.end (/usr/lib/node_modules/browserify/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:436:5)
    at DuplexWrapper.onend (/usr/lib/node_modules/browserify/node_modules/duplexer2/node_modules/readable-stream/lib/_stream_readable.js:537:10)
    at DuplexWrapper.g (events.js:175:14)
```

**Comment by goto-bus-stop** [comment]
Cleaning up old issues, please open a new one if this is still relevant
