### ISSUE TITLE
Getting error while converting require('usb') to browserify.. please help

### ISSUE THREAD

**Issue by panneerselvampst** [browserify/browserify#1579]
if (stream._ansicursor) {
           ^

ypeError: Cannot read property '_ansicursor' of undefined
   at ansi (D:\Users\one\nodejs\browserify\usbbundle.js:2908:13)
   at Object.<anonymous> (D:\Users\one\nodejs\browserify\usbbundle.js:2570
14)
   at Object.__dirname.11._process (D:\Users\one\nodejs\browserify\usbbund
e.js:2814:4)
   at s (D:\Users\one\nodejs\browserify\usbbundle.js:1:316)
   at D:\Users\one\nodejs\browserify\usbbundle.js:1:367
   at Object.<anonymous> (D:\Users\one\nodejs\browserify\usbbundle.js:387:
1)
   at Object.__dirname.5.../package (D:\Users\pthanga2\nodejs\browserify\usbbun
le.js:566:4)
   at s (D:\Users\one\nodejs\browserify\usbbundle.js:1:316)
   at D:\Users\one\nodejs\browserify\usbbundle.js:1:367
   at Object.<anonymous> (D:\Users\one\nodejs\browserify\usbbundle.js:8630
14)

:\Users\one\nodejs\browserify>node usbbundle.js --verbose
:\Users\one\nodejs\browserify\usbbundle.js:2908
 if (stream._ansicursor) {
           ^

ypeError: Cannot read property '_ansicursor' of undefined
   at ansi (D:\Users\one\nodejs\browserify\usbbundle.js:2908:13)
   at Object.<anonymous> (D:\Users\one\nodejs\browserify\usbbundle.js:2570
14)
   at Object.__dirname.11._process (D:\Users\one\nodejs\browserify\usbbund
e.js:2814:4)
   at s (D:\Users\one\nodejs\browserify\usbbundle.js:1:316)
   at D:\Users\one\nodejs\browserify\usbbundle.js:1:367
   at Object.<anonymous> (D:\Users\one\nodejs\browserify\usbbundle.js:387:
1)
   at Object.__dirname.5.../package (D:\Users\one\nodejs\browserify\usbbun
le.js:566:4)
   at s (D:\Users\one\nodejs\browserify\usbbundle.js:1:316)
   at D:\Users\one\nodejs\browserify\usbbundle.js:1:367
   at Object.<anonymous> (D:\Users\one\nodejs\browserify\usbbundle.js:8630

**Comment by goto-bus-stop** [comment]
`usb` is a native module, it does not work in the browser.
