### ISSUE TITLE
Error: premature close

### ISSUE THREAD

**Issue by SeanSobey** [browserify/browserify#1792]
I am getting this error on a previously working gulp build using browserify:
```
[11:41:55] Using gulpfile ~<ROOT>\gulpfile.js
[11:41:55] Starting 'build:browserify'...
[11:41:55] 'build:browserify' errored after 282 ms
[11:41:55] Error: premature close
    at Pumpify.onclose (<ROOT>\node_modules\end-of-stream\index.js:43:67)
    at Pumpify.emit (events.js:159:13)
    at Pumpify.Duplexify._destroy (<ROOT>\node_modules\duplexify\index.js:192:8)
    at <ROOT>\node_modules\duplexify\index.js:175:10
    at process._tickCallback (internal/process/next_tick.js:150:11)
The terminal process terminated with exit code: 1
```
The gulp task looks like this:
```js
task('build:browserify', () => {
	return browserify({
			debug: true
		})
		.require('./dist/Xero/Cards/ChartConfigurations/index.js', {
			expose: 'chartConfigs'
		})
		.require('./dist/ChartJs/index.js', {
			expose: 'chartJs'
		})
		.bundle()
		.pipe(source('app.js'))
		.pipe(gulp.dest('./site/Scripts/'));
});
```

Using browserify version 14.5.0 on Node 9.3.0.

**Comment by SeanSobey** [comment]
Upon some further investigation, I think I have identified the issue, which seems between node and the [end-of-stream](https://github.com/mafintosh/end-of-stream) library used by gulp (4.0):

https://github.com/mafintosh/end-of-stream/issues/14
https://github.com/nodejs/node/issues/15029

It looks like this will only be reverted in node version 8.6.0.
