### ISSUE TITLE
Stream Non-Entry Files

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [browserify/browserify#1813]
I'm trying to also stream files that the entry file requires is this possible?
I have been looking for a while and haven't found innate to browserify or a plugin.

Simplified Example:
```javascript
const str = require('string-to-stream');
const browserify = require('browserify');

const entry = "const func = require('./func.js')";
const func = "module.exports = function() {return 'func'}";

browserify(str(entry), {basedir: __dirname})
  // somehow map './func.js' to func string
```

**Comment by goto-bus-stop** [comment]
Hmm I don't think this is really possible, as `./func.js` will always be resolved relative to the basedir and files are read using `fs.readFile`.

You can sort of approach it by using the `fileCache` option from module-deps, which maps absolute file paths to contents:

```js
browserify(str(entry), {
  basedir: __dirname,
  fileCache: {
    [__dirname + '/func.js']: func
  }
})
```

but that is not great either :woman_shrugging:

**Comment by BebeSparkelSparkel** [comment]
I found a related issue #1417 
But didn't see the `__dirname + '/func.js'` part there

**Comment by BebeSparkelSparkel** [comment]
Actually I cannot get this to work correctly

```javascript
const str = require('string-to-stream')
const browserify = require('browserify')
const concat = require('concat-stream-promise')


const entry = "const func = require('./func.js')"

const fileCache = {
  [__dirname + '/func.js']: "module.exports = function() {return 'func'}",
}

browserify(str(entry), {basedir: __dirname, fileCache})
  .bundle()
  .pipe(concat())
  .then(() => console.log('Completed corretly'))
  .catch(console.error.bind(console))
```

Error:
```bash
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find module './func.js' from '/Users/williamrusnack/Documents/form_database'
    at /Users/williamrusnack/Documents/form_database/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
    at load (/Users/williamrusnack/Documents/form_database/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/williamrusnack/Documents/form_database/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /Users/williamrusnack/Documents/form_database/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:153:21)
```

**Comment by mattdesl** [comment]
I am doing some similar things in my tools, generating source on the fly in response to certain require statements. If you are OK with requiring a module name like `'foo-bar'` rather than relative path, you can do this:

```js
const fromStr = require('from2-string');
const browserify = require('browserify');

const entry = `module.exports = require('foo-bar');`;
const other = `module.exports = "foobar";`;

const b = browserify(fromStr(entry), {
  basedir: __dirname
});

b.exclude('foo-bar');
b.require(fromStr(other), {
  // Make up a file name for the stream
  // If the file name is within node_modules, then
  // it will get skipped by non-global transforms
  file: 'foo-bar.js',
  expose: 'foo-bar'
});

b.bundle((err, src) => {
  if (err) throw err;
  console.log(src.toString());
});
```

If you need relative file names like `./foo-bar.js`, you may have to dive into plugins, potentially doing something like altering the `.source` property as rows come through the pipeline, if the id matches the file you are trying to modify.

**Comment by BebeSparkelSparkel** [comment]
@mattdesl That works great!

I've tried to write a small plugin for this. Could you check if it makes sense and suggest better variable names?

Plugin:
```javascript
function require_string_plugin(b, opts) {
  b.require_string = function (name2code, extension='.js') {
    for (const name in name2code) {
      if (name2code.hasOwnProperty(name)) {
        this
          .exclude(name)
          .require(str(name2code[name]), {
            file: name + extension,
            expose: name,
          })
      }
    }
    return this
  }
}
```

Here is an example of it in use:
```javascript
const str = require('string-to-stream')
const browserify = require('browserify')
const concat = require('concat-stream-promise')


const entry = `
  const func0 = require('func0')
  const func1 = require('func1')
  func0()
  func1()
`

const name2code = {
  func0: 'module.exports = function() {console.log("func0")}',
  func1: 'module.exports = function() {console.log("func1")}',
}

browserify(str(entry), {basedir: __dirname})

  // require_string_plugin
  .plugin(require_string_plugin)
  .require_string(name2code)

  .bundle()
  .pipe(concat())
  .then(bundle_buff => bundle_buff.toString('utf8'))

  .then(bundle => {
    console.log('Completed corretly')
    console.log(bundle)
    console.log('eval(bundle):'); eval(bundle)
    console.log('----------------------------------------------\n\n')
  })
  .catch(console.error.bind(console))
```

Example Output:
```bash
Completed corretly
require=(function(){function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s}return e})()({1:[function(require,module,exports){

  const func0 = require('func0')
  const func1 = require('func1')
  func0()
  func1()

},{"func0":"func0","func1":"func1"}],"func0":[function(require,module,exports){
module.exports = function() {console.log("func0")}
},{}],"func1":[function(require,module,exports){
module.exports = function() {console.log("func1")}
},{}]},{},[1]);

eval(bundle):
func0
func1
----------------------------------------------
```

**Comment by BebeSparkelSparkel** [comment]
Repo for plugin [require_stringify](https://github.com/BebeSparkelSparkel/require_stringify)
