### ISSUE TITLE
Browserify failing to apply transformations to monorepo package

### ISSUE THREAD

**Issue by miguel-guedes** [browserify/browserify#1867]
I am unable to run browserify (via gulp-browserify) with a babelify transform on Javascript source files.  The code lives inside a monorepo that has the following structure:

```
the-project
  packages
    library
      index.js
    app
      main.js
```

`app/main.js` contains the following code:
```js
// @flow

import { test } from "libzotero";

test(1, 2, 3);
console.log("done.");
```

`library/index.js` contains simply:
```js
// @flow

function test(...args: Array<any>): number {
  return args.length;
}

export { test };
```

Running browserify from within `app` results in the following:
```
packages/app $ ../../node_modules/.bin/browserify -t babelify main.js
SyntaxError: /path/to/project/node_modules/libzotero/index.js: Unexpected token, expected ")" (3:21)

  1 | // @flow
  2 | 
> 3 | function test(...args: Array<any>): number {
    |                      ^
  4 |   console.log("TEST! Args:", args);
  5 |   return args.length;
  6 | }
    at Parser.raise (/path/to/project/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:3939:15)
    at Parser.unexpected (/path/to/project/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:5248:16)
    at Parser.expect (/path/to/project/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:5236:28)
    at Parser.parseBindingList (/path/to/project/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:5529:14)
    at Parser.parseFunctionParams (/path/to/project/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:7833:24)
    at Parser.parseFunction (/path/to/project/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:7820:10)
    at Parser.parseFunctionStatement (/path/to/project/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:7476:17)
    at Parser.parseStatementContent (/path/to/project/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:7169:21)
    at Parser.parseStatement (/path/to/project/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:7145:17)
    at Parser.parseBlockOrModuleBlockBody (/path/to/project/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:7696:23)
```

It seems that browserify is ignoring babel(ify) transformations on any source files in `library`.  What can be done about this?

**Comment by miguel-guedes** [comment]
Turned out to be an issue with babel.
