### ISSUE TITLE
BigInt literals cause parse error in some cases

### ISSUE THREAD

**Issue by dmishin** [browserify/browserify#1989]
The following code, using BigInt literal, causes browserify to barf:
```` js
    //require
    console.log(255n);
````
Interestingly, if the initial comment line is removed, there is no error, and correct output is produced.
The error is:
````
Error: Parsing file /home/dim/Prog/minkovsky-ca/sample.js: Identifier directly after number (4:17)
    at Deps.parseDeps (/usr/lib/node_modules/browserify/node_modules/module-deps/index.js:481:28)
    at getDeps (/usr/lib/node_modules/browserify/node_modules/module-deps/index.js:414:40)
    at /usr/lib/node_modules/browserify/node_modules/module-deps/index.js:398:32
    at ConcatStream.<anonymous> (/usr/lib/node_modules/browserify/node_modules/concat-stream/index.js:36:43)
    at ConcatStream.emit (node:events:388:22)
    at finishMaybe (/usr/lib/node_modules/browserify/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:475:14)
    at endWritable (/usr/lib/node_modules/browserify/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:485:3)
    at ConcatStream.Writable.end (/usr/lib/node_modules/browserify/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:455:41)
    at DuplexWrapper.onend (/usr/lib/node_modules/browserify/node_modules/readable-stream/lib/_stream_readable.js:570:10)
    at Object.onceWrapper (node:events:482:28)
````

My browserify version is 17.0.0

**Comment by dmishin** [comment]
Sorry, my mistake. After looking twice at the log, I now see that older version installed globally was running. Version 17.0.0 works fine.
