### ISSUE TITLE
Add support for node: protocol

### ISSUE THREAD

**Issue by kptdobe** [browserify/browserify#2019]
The `node:` protocol (https://github.com/nodejs/node/issues/38343) does not seem to be supported or I do not think how to "make it happen".

main.js

```
import { toMdast } from 'hast-util-to-mdast';
```

Install:

```
npm install --save-dev esmify browserify
npm install hast-util-to-mdast
```

Run:

```
npx browserify -p esmify main.js -o bundle.js
```

Output:
```
Error: Can't walk dependency graph: Cannot find module 'node:url' from 'node_modules/hast-util-to-mdast/lib/util/resolve.js'
```

The library uses the `node:` protocole: https://github.com/syntax-tree/hast-util-to-mdast/blob/main/lib/util/resolve.js#L5

Any hint to resolve this would be really appreciated!
Thanks

**Comment by ljharb** [comment]
What version of node are you using?

**Comment by kptdobe** [comment]
I have tried v14.17.5 and v16.9.1. Same for both.

**Comment by ljharb** [comment]
node 14 doesn't support the `node:` protocol in CJS, and the `resolve` package (and `is-core-module`) handle CJS, so you'd need node 16.

What version of browserify are you using? What version of resolve is in your dep tree?

**Comment by kptdobe** [comment]
```
browserify: "17.0.0"
resolve: "1.20.0"
is-core-module: "2.6.0"
```

**Comment by ljharb** [comment]
That's definitely late enough.

The issue might be that the unifiedjs packages have gone ESM-only, and `resolve` (as well as most of the ecosystem) doesn't yet support that. However, `node:url` resolves in CJS, so I remain confused.

Is that the entire error output? A stack trace would be helpful.

**Comment by kptdobe** [comment]
Sorry I summarised but with node 16, I only get:

```
 Error: Can't walk dependency graph: ENOENT: no such file or directory, lstat '[...]/node:url'
    required by [...]/node_modules/hast-util-to-mdast/lib/util/resolve.js
``` 

with node 14, I get a little more:

```
Error: Can't walk dependency graph: Cannot find module 'node:url' from 'node_modules/hast-util-to-mdast/lib/util/resolve.js'
    required by [...]/node_modules/hast-util-to-mdast/lib/util/resolve.js
    at [...]/node_modules/esmify/esmify.js:47:19
    at [...]/node_modules/browser-resolve/index.js:265:24
    at [...]/node_modules/resolve/lib/async.js:139:17
    at processDirs ([...]/node_modules/resolve/lib/async.js:290:39)
    at isdir ([...]/node_modules/resolve/lib/async.js:297:32)
    at [...]/node_modules/resolve/lib/async.js:25:69
    at FSReqCallback.oncomplete (fs.js:192:21)
```

**Comment by ljharb** [comment]
Seems like esmify or browser-resolve probably needs special handling so that `node:url` is aliased to `url`.

**Comment by robertsLando** [comment]
Any news on this? I have the same problem

**Comment by errodrigues** [comment]
Same issue here. Ajv just release 8.15.0 where they introduced a dependency on fast-uri, which uses the `node:url` notation and breaks our use of browserify

**Comment by ljharb** [comment]
@errodrigues it might be worth filing an issue on fast-uri to see if they can use the more backwards-compatible notation.

**Comment by errodrigues** [comment]
We started evaluating esbuild. Looks promising. Thanks for the suggestion.
