### ISSUE TITLE
Can't parse ES2020

### ISSUE THREAD

**Issue by falsandtru** [browserify/browserify#2020]
Could you support ES2021?

```console
$ node_modules/.bin/browserify src/random.js
SyntaxError: Unexpected token (3:4) while parsing ...\src\random.js while parsing file: ...\src\random.js
    at DestroyableTransform.end [as _flush] (...\node_modules\insert-module-globals\index.js:114:21)
    at DestroyableTransform.prefinish (...\node_modules\readable-stream\lib\_stream_transform.js:138:10)
    at DestroyableTransform.emit (node:events:394:28)
    at prefinish (...\node_modules\readable-stream\lib\_stream_writable.js:619:14)
    at finishMaybe (...\node_modules\readable-stream\lib\_stream_writable.js:627:5)
    at endWritable (...\node_modules\readable-stream\lib\_stream_writable.js:638:3)
    at DestroyableTransform.Writable.end (...\node_modules\readable-stream\lib\_stream_writable.js:594:41)
    at DestroyableTransform.onend (...\node_modules\readable-stream\lib\_stream_readable.js:577:10)
    at Object.onceWrapper (node:events:513:28)
    at DestroyableTransform.emit (node:events:406:35)
```

```js
// random.js
require("./global");
let a;
a ??= 0;

// global.js
0
```

**Comment by henriqueleite42** [comment]
Do we have any workarounds for this? `noParse` seems not to work

**Comment by mikixing** [comment]
您的邮件我已收到，会尽快查阅~

**Comment by davidmurdoch** [comment]
This is happening because in the dependency `module-deps/index.js`, the call to `self.detective` in `Deps.prototype.parseDeps` needs to pass in parse options. Changing the line

```
try { var deps = self.detective(src) }
```

to

```
try { var deps = self.detective(src, { parse: { ecmaVersion: 12 } }) }
```

"fixes" it.
