### ISSUE TITLE
General Question: Trying to bundle Handbrake-JS with Browserify

### ISSUE THREAD

**Issue by inglesuniversal** [browserify/browserify#2021]
Hi, I followed your instructions and got this Error:

    browserify main.js -o bundle.js
    SyntaxError: 'import' and 'export' may appear only with 'sourceType: module' (1:0) while parsing /Users/LOCALHOST/NodeJS/handbrake-web/node_modules/handbrake-js/index.js while parsing file: /Users/LOCALHOST/NodeJS/handbrake-web/node_modules/handbrake-js/index.js
        at DestroyableTransform.end [as _flush] (/usr/local/lib/node_modules/browserify/node_modules/insert-module-globals/index.js:114:21)
        at DestroyableTransform.prefinish (/usr/local/lib/node_modules/browserify/node_modules/readable-stream/lib/_stream_transform.js:138:10)
        at DestroyableTransform.emit (node:events:394:28)
        at prefinish (/usr/local/lib/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:619:14)
        at finishMaybe (/usr/local/lib/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:627:5)
        at endWritable (/usr/local/lib/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:638:3)
        at DestroyableTransform.Writable.end (/usr/local/lib/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:594:41)
        at DestroyableTransform.onend (/usr/local/lib/node_modules/browserify/node_modules/readable-stream/lib/_stream_readable.js:577:10)
        at Object.onceWrapper (node:events:513:28)
        at DestroyableTransform.emit (node:events:406:35)

MAIN.JS

    const hbjs = require('handbrake-js')

    const urlParams = new URLSearchParams(window.location.search);
    const input = urlParams.get('input');
    const output = urlParams.get('output');

    hbjs.spawn({ input: input, output: output })
    .on('error', err => {
        // invalid user input, no video found etc
        console.log(`err: ${err}`);
    })
    .on('progress', progress => {
        console.log(
        'Percent complete: %s, ETA: %s',
        progress.percentComplete,
        progress.eta
        )
    })

**Comment by goto-bus-stop** [comment]
the `import`/`export` error could be solved using the [esmify](https://www.npmjs.com/package/esmify) transform. however, handbrake-js would still not work. It appears to rely on a command line tool, which is impossible to run in the browser.
