### ISSUE TITLE
'MODULE_NOT_FOUND' Error

### ISSUE THREAD

**Issue by Jodscho** [browserify/browserify#2037]
Hi,
i followed the small tutorial at: https://browserify.org/#install and everything worked fine.
browserify does not complain if i run it with the following example. But if i then try to run the program (_node bundle.js_) i get the following error:
```javascript
const BM = require('bookmark-parser')
console.log("test")
```

**Error:**
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '/node_modules/bookmark-parser/lib/bookmark_parser/jsonlz4_parser'
Require stack:
- /home/jonathan/Documents/ffutil/out.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at o (/home/jonathan/Documents/ffutil/out.js:1:125)
    at /home/jonathan/Documents/ffutil/out.js:1:316
    at Object.<anonymous> (/home/jonathan/Documents/ffutil/out.js:5801:23)
    at Object.<anonymous> (/home/jonathan/Documents/ffutil/out.js:5875:4)
    at Object.4.bluebird (/home/jonathan/Documents/ffutil/out.js:5875:17)
    at o (/home/jonathan/Documents/ffutil/out.js:1:265)
    at /home/jonathan/Documents/ffutil/out.js:1:316
    at Object.3../lib (/home/jonathan/Documents/ffutil/out.js:5789:18)
    at o (/home/jonathan/Documents/ffutil/out.js:1:265)
    at /home/jonathan/Documents/ffutil/out.js:1:316
    at Object.1.bookmark-parser (/home/jonathan/Documents/ffutil/out.js:2:12)
    at o (/home/jonathan/Documents/ffutil/out.js:1:265) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/jonathan/Documents/ffutil/out.js' ]
}

npm version: 8.5.5
node version: 17.9
( i ran the same example with a freshly installed linux mint, same error)

**Comment by ljharb** [comment]
The package is, for no good reason, doing a dynamic require instead of a static one: https://unpkg.com/browse/bookmark-parser@0.1.6/lib/index.js

This will break with any bundlers. I’d suggest filing an issue with it.

**Comment by Jodscho** [comment]
I will do that, thank you!
