### ISSUE TITLE
SyntaxError: Unexpected token (53:4) while parsing 

### ISSUE THREAD

**Issue by paulcoffee85** [browserify/browserify#2054]
The error whenever trying to use command:

$ `yarn browserify index.js --standalone bundle -o ./dist/bundle.js`
with file that has `const { ethers } = require("ethers");`  in it.  Otherwise how do you add that require after process if possible ??
```
$ C:\Users\paulc\ConnectSmartContracts2MM\node_modules\.bin\browserify index.js --standalone bundle -o ./dist/bundle.js
SyntaxError: Unexpected token (53:4) while parsing C:\Users\paulc\ConnectSmartContracts2MM\node_modules\ethers\lib.commonjs\abi\fragments.js while parsing file: C:\Users\paulc\ConnectSmartContracts2MM\node_modules\ethers\lib.commonjs\abi\fragments.js
    at DestroyableTransform.end [as _flush] (C:\Users\paulc\ConnectSmartContracts2MM\node_modules\insert-module-globals\index.js:114:21)
    at DestroyableTransform.prefinish (C:\Users\paulc\ConnectSmartContracts2MM\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:138:10)
    at DestroyableTransform.emit (node:events:513:28)
    at prefinish (C:\Users\paulc\ConnectSmartContracts2MM\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:619:14)
    at finishMaybe (C:\Users\paulc\ConnectSmartContracts2MM\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:627:5)
    at endWritable (C:\Users\paulc\ConnectSmartContracts2MM\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:638:3)
    at Writable.end (C:\Users\paulc\ConnectSmartContracts2MM\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:594:22)
    at DestroyableTransform.onend (C:\Users\paulc\ConnectSmartContracts2MM\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:577:10)
    at Object.onceWrapper (node:events:627:28)
    at DestroyableTransform.emit (node:events:525:35)

**Comment by paulcoffee85** [comment]
Nevermind, if someone had frick'n mentioned `watchify`, half the errors would have never appeared

**Comment by ygorz** [comment]
> Nevermind, if someone had frick'n mentioned `watchify`, half the errors would have never appeared

How did you get this to run exactly? I'm having the same issue.

**Comment by mikixing** [comment]
您的邮件我已收到，会尽快查阅~

**Comment by ebousse** [comment]
I encounter a similar problem with version `17.0.1`:

```
SyntaxError: Unexpected token (7962:50) while parsing /home/bousse-e/git/code/edt-extractor-web/node_modules/ical.js/dist/ical.js while parsing file: /home/bousse-e/git/code/edt-extractor-web/node_modules/ical.js/dist/ical.js
    at DestroyableTransform.end [as _flush] (/home/bousse-e/git/code/edt-extractor-web/node_modules/insert-module-globals/index.js:114:21)
    at DestroyableTransform.prefinish (/home/bousse-e/git/code/edt-extractor-web/node_modules/readable-stream/lib/_stream_transform.js:138:10)
    at DestroyableTransform.emit (node:events:518:28)
    at prefinish (/home/bousse-e/git/code/edt-extractor-web/node_modules/readable-stream/lib/_stream_writable.js:619:14)
    at finishMaybe (/home/bousse-e/git/code/edt-extractor-web/node_modules/readable-stream/lib/_stream_writable.js:627:5)
    at endWritable (/home/bousse-e/git/code/edt-extractor-web/node_modules/readable-stream/lib/_stream_writable.js:638:3)
    at Writable.end (/home/bousse-e/git/code/edt-extractor-web/node_modules/readable-stream/lib/_stream_writable.js:594:41)
    at DestroyableTransform.onend (/home/bousse-e/git/code/edt-extractor-web/node_modules/readable-stream/lib/_stream_readable.js:577:10)
    at Object.onceWrapper (node:events:632:28)
    at DestroyableTransform.emit (node:events:530:35)
bousse-e at mohnstrudel in ~/g/c/edt-extractor-web (maste
```

Here is line `7962` of `ical.js`:

```js
      let versionProp = this.jCal[PROPERTY_INDEX]?.[0];
```

**Comment by mikixing** [comment]
您的邮件我已收到，会尽快查阅~
