### ISSUE TITLE
Unexpected character '#'

### ISSUE THREAD

**Issue by afdapone** [browserify/browserify#2056]
I am having this error "Unexpected character '#'" when trying to bundle my JS code. I version 17.0.0 which is the latest version as of now. How can I fix this? The error code is below:

PS P:\devProjects\eSvrApps\nep-vfl-2> browserify --node --ignore-missing main.js -o bundle.js
Error: Parsing file P:\devProjects\eSvrApps\nep-vfl-2\node_modules\chromium-bidi\lib\cjs\bidiMapper\CommandProcessor.js: Unexpected character '#' (70:10)
    at Deps.parseDeps (O:\devTools\node-v16.17.0-win-x64\node_modules\browserify\node_modules\module-deps\index.js:519:15)
    at getDeps (O:\devTools\node-v16.17.0-win-x64\node_modules\browserify\node_modules\module-deps\index.js:447:44)
    at O:\devTools\node-v16.17.0-win-x64\node_modules\browserify\node_modules\module-deps\index.js:430:38
    at ConcatStream.<anonymous> (O:\devTools\node-v16.17.0-win-x64\node_modules\browserify\node_modules\concat-stream\index.js:37:43)
    at ConcatStream.emit (node:events:525:35)
    at finishMaybe (O:\devTools\node-v16.17.0-win-x64\node_modules\browserify\node_modules\readable-stream\lib\_stream_writable.js:630:14)
    at endWritable (O:\devTools\node-v16.17.0-win-x64\node_modules\browserify\node_modules\readable-stream\lib\_stream_writable.js:638:3)
    at ConcatStream.Writable.end (O:\devTools\node-v16.17.0-win-x64\node_modules\browserify\node_modules\readable-stream\lib\_stream_writable.js:594:41)
    at DuplexWrapper.onend (O:\devTools\node-v16.17.0-win-x64\node_modules\browserify\node_modules\readable-stream\lib\_stream_readable.js:577:10)
    at Object.onceWrapper (node:events:627:28)

**Comment by PanagiotisDrakatos** [comment]
@afdapone I am facing a similar issue i was forced to delete the # which indicates a private field but this is not a solution maybe @goto-bus-stop knows the answer :P.

**Comment by hollandjake** [comment]
Any update on this?
