### ISSUE TITLE
TypeError: this.buffers[pos.buf].get is not a function

### ISSUE THREAD

**Issue by lh12565** [browserify/browserify#2061]
Hi when I run browserify, there is a error as below:
```
browserify -t browserify-css -t svgify ../test/node_modules/react-mutation-mapper/dist/index.js -o all.js


/NAS/lh/down/npm_Data/browserify/node_modules/buffers/index.js:185
    return this.buffers[pos.buf].get(pos.offset);
                                 ^

TypeError: this.buffers[pos.buf].get is not a function
    at Buffers.get (/NAS/lh/down/npm_Data/browserify/node_modules/buffers/index.js:185:34)
    at makeFn (/NAS/lh/down/npm_Data/browserify/node_modules/trumpet/lib/tokenize.js:56:26)
    at SAXStream.parser.<computed> (/NAS/lh/down/npm_Data/browserify/node_modules/trumpet/lib/tokenize.js:25:50)
    at SAXStream.emit (node:events:329:20)
    at SAXParser.me._parser.<computed> [as onopentag] (/NAS/lh/down/npm_Data/browserify/node_modules/sax/lib/sax.js:245:15)
    at emit (/NAS/lh/down/npm_Data/browserify/node_modules/sax/lib/sax.js:615:33)
    at emitNode (/NAS/lh/down/npm_Data/browserify/node_modules/sax/lib/sax.js:620:3)
    at openTag (/NAS/lh/down/npm_Data/browserify/node_modules/sax/lib/sax.js:801:3)
    at SAXParser.write (/NAS/lh/down/npm_Data/browserify/node_modules/sax/lib/sax.js:1260:31)
    at SAXStream.write (/NAS/lh/down/npm_Data/browserify/node_modules/sax/lib/sax.js:227:16)
```
Please help me how to solve it.
Thanks!

**Comment by davmillar** [comment]
@lh12565 some of the dependencies have changed since you originally wrote this issue -- if you are still working on this project, can you share whether the newest version of browserify works in your use case, or if you found a resolution since then?
