### ISSUE TITLE
browserify error with webtorrent

### ISSUE THREAD

**Issue by adarshchri** [browserify/browserify#2067]
@feross 

browserify index.js -o bundle.js

SyntaxError: 'import' and 'export' may appear only with 'sourceType: module' (2:0) while parsing C:\Users\chaud\Desktop\webtor\node_modules\webtorrent\index.js while parsing file: C:\Users\chaud\Desktop\webtor\node_modules\webtorrent\index.js
    at DestroyableTransform.end [as _flush] (C:\Users\chaud\AppData\Roaming\npm\node_modules\browserify\node_modules\insert-module-globals\index.js:114:21)
    at DestroyableTransform.prefinish (C:\Users\chaud\AppData\Roaming\npm\node_modules\browserify\node_modules\readable-stream\lib\_stream_transform.js:138:10)
    at DestroyableTransform.emit (node:events:513:28)
    at prefinish (C:\Users\chaud\AppData\Roaming\npm\node_modules\browserify\node_modules\readable-stream\lib\_stream_writable.js:619:14)
    at finishMaybe (C:\Users\chaud\AppData\Roaming\npm\node_modules\browserify\node_modules\readable-stream\lib\_stream_writable.js:627:5)
    at endWritable (C:\Users\chaud\AppData\Roaming\npm\node_modules\browserify\node_modules\readable-stream\lib\_stream_writable.js:638:3)
    at Writable.end (C:\Users\chaud\AppData\Roaming\npm\node_modules\browserify\node_modules\readable-stream\lib\_stream_writable.js:594:22)
    at DestroyableTransform.onend (C:\Users\chaud\AppData\Roaming\npm\node_modules\browserify\node_modules\readable-stream\lib\_stream_readable.js:577:10)
    at Object.onceWrapper (node:events:627:28)
    at DestroyableTransform.emit (node:events:525:35)

**Comment by adarshchri** [comment]
package.json

{
  "name": "webtor",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "browserify": "^17.0.0",
    "webtorrent": "^2.1.12"
  }
}

**Comment by adarshchri** [comment]
**index.js**

// Including modules
const WebTorrent = require("webtorrent");
// Initializing WebTorrent
const client = new WebTorrent();

// Using a magnet link
let NewMagnetTorrentId =
  "magnet:?xt=urn:btih:08ada5a7a6183aae1e09d831df6748d566095a10&dn=Sintel&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337&tr=udp%3A%2F%2Fexplodie.org%3A6969&tr=udp%3A%2F%2Ftracker.empire-js.us%3A1337&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.openwebtorrent.com&tr=wss%3A%2F%2Ftracker.fastcast.nz&ws=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2F";
// Starts downloading a new torrent file
client.add(NewMagnetTorrentId, function (torrent) {
  // Using the .mp4 file
  const file = torrent.files.find(function (Newfile) {
    // Returning filename ending with .mp4
    return Newfile.name.endsWith(".mp4");
  });

  // Display the file by adding it to the DOM.
  file.appendTo("body");
});

**Comment by davmillar** [comment]
@adarshchri based on the example at https://github.com/webtorrent/webtorrent/blob/master/docs/get-started.md#browserify-and-webpack it looks like you're going to want to write your index.js file using import instead of require, rename it to index.mjs, then use browserify to compile it.
