### ISSUE TITLE
Browserify + common-shakeify + Chart.js = infinite stack trace

### ISSUE THREAD

**Issue by ile** [browserify/browserify#2069]
I created this issue here: https://github.com/chartjs/Chart.js/issues/11479

### Expected behavior

I'm using browserify@17.0.0 + common-shakeify@1.1.2 +  chart.js@4.4.0.

In JavaScript I have this:

```js
const Chart = require('chart.js/auto');

console.log('Hello');
```

Bundling will give me a stack trace and a crash.

### Current behavior

```
ile@ilepc:~/src/sc2/browserify-chartjs$ ./run.sh 
/home/ile/src/sc2/browserify-chartjs/node_modules/escope/lib/scope.js:417
            var ref = new _reference2.default(node, this, assign || _reference2.default.READ, writeExpr, maybeImplicitGlobal, !!partial, !!init);
                      ^

RangeError: Maximum call stack size exceeded
    at ClassScope.__referencing (/home/ile/src/sc2/browserify-chartjs/node_modules/escope/lib/scope.js:417:23)
    at Referencer.Identifier (/home/ile/src/sc2/browserify-chartjs/node_modules/escope/lib/referencer.js:425:33)
    at Visitor.visit (/home/ile/src/sc2/browserify-chartjs/node_modules/esrecurse/esrecurse.js:104:34)
    at Visitor.visitChildren (/home/ile/src/sc2/browserify-chartjs/node_modules/esrecurse/esrecurse.js:88:26)
    at Visitor.visit (/home/ile/src/sc2/browserify-chartjs/node_modules/esrecurse/esrecurse.js:107:14)
    at Visitor.visitChildren (/home/ile/src/sc2/browserify-chartjs/node_modules/esrecurse/esrecurse.js:83:38)
    at Visitor.visit (/home/ile/src/sc2/browserify-chartjs/node_modules/esrecurse/esrecurse.js:107:14)
    at Visitor.visitChildren (/home/ile/src/sc2/browserify-chartjs/node_modules/esrecurse/esrecurse.js:88:26)
    at Visitor.visit (/home/ile/src/sc2/browserify-chartjs/node_modules/esrecurse/esrecurse.js:107:14)
    at Visitor.visitChildren (/home/ile/src/sc2/browserify-chartjs/node_modules/esrecurse/esrecurse.js:83:38)

Node.js v20.5.1
```

### Reproducible sample

https://github.com/ile/browserify-chartjs

### chart.js version

v4.4.0

### Link to your project

https://github.com/ile/browserify-chartjs

**Comment by mikixing** [comment]
您的邮件我已收到，会尽快查阅~

**Comment by ile** [comment]
The issue was `es2022`, which common-shakeify couldn't handle. It could handle `es2021`. 

Here: https://github.com/chartjs/Chart.js/blob/master/rollup.config.js#L28

I opened this issue also in browserify repo, please close the other. https://github.com/browserify/common-shakeify/issues/52
