### ISSUE TITLE
b.add(file, opts) does not work with file being an array

### ISSUE THREAD

**Issue by domenic** [browserify/browserify#873]
But the docs say it should.

`b.add('a').add('b')` works. `b.add(['a', 'b'])` gives Error: path must be a string

```
Uncaught Error: path must be a string
----------------------------------------
    at EventEmitter.on
    at makeWrappedCallback (c:\Chocolatey\lib\nodist.0.4.6-beta\tools\nodist-master\bin\node_modules\tracer-bullet\node_modules\long-stack-traces\lib\long-stack-traces.js:65:26)
    at Labeled.object.(anonymous function) (c:\Chocolatey\lib\nodist.0.4.6-beta\tools\nodist-master\bin\node_modules\tracer-bullet\node_modules\long-stack-traces\lib\long-stack-traces.js:51:38)
    at Labeled.Readable.on (c:\Users\Domenic\Dropbox\GitHub\dglazkov\html-as-custom-elements\node_modules\browserify\node_modules\labeled-stream-splicer\node_modules\stream-splicer\node_modules\readable-stream\lib\_stream_readable.js:703:33)
    at c:\Users\Domenic\Dropbox\GitHub\dglazkov\html-as-custom-elements\node_modules\browserify\node_modules\labeled-stream-splicer\node_modules\stream-splicer\index.js:129:16
    at Labeled.Pipeline.splice (c:\Users\Domenic\Dropbox\GitHub\dglazkov\html-as-custom-elements\node_modules\browserify\node_modules\labeled-stream-splicer\node_modules\stream-splicer\index.js:141:7)
    at Labeled.splice (c:\Users\Domenic\Dropbox\GitHub\dglazkov\html-as-custom-elements\node_modules\browserify\node_modules\labeled-stream-splicer\index.js:64:37)
    at new Labeled (c:\Users\Domenic\Dropbox\GitHub\dglazkov\html-as-custom-elements\node_modules\browserify\node_modules\labeled-stream-splicer\index.js:33:17)
    at Function.module.exports.obj (c:\Users\Domenic\Dropbox\GitHub\dglazkov\html-as-custom-elements\node_modules\browserify\node_modules\labeled-stream-splicer\index.js:11:12)
    at Browserify._createPipeline (c:\Users\Domenic\Dropbox\GitHub\dglazkov\html-as-custom-elements\node_modules\browserify\index.js:251:28)
    at new Browserify (c:\Users\Domenic\Dropbox\GitHub\dglazkov\html-as-custom-elements\node_modules\browserify\index.js:54:26)
Uncaught undefined
Uncaught undefined

c:\Chocolatey\lib\nodist.0.4.6-beta\tools\nodist-master\bin\node_modules\tracer-bullet\node_modules\long-stack-traces\lib\long-stack-traces.js:80
                    throw ""; // TODO: throw the original error, or undefined?
                    ^
```

**Comment by goto-bus-stop** [comment]
fixed in 6f024042
