### ISSUE TITLE
Globals when doing --global-transform - window undefined

### ISSUE THREAD

**Issue by kevinsimper** [browserify/browserify#983]
I am trying to do a global transform with `brfs` on a module, but globals is not defined in external modules. 

I have tried using `--insert-globals` but it did not help

```
$ browserify test.js -o bundle.js --transform brfs -g crafty --insert-globals

/xxx/node_modules/crafty/src/2D.js:2
    document = window.document,
               ^
ReferenceError: window is not defined
    at Object.<anonymous> (/xxx/node_modules/crafty/src/2D.js:2:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/xxx/node_modules/crafty/src/crafty.js:2:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

**Comment by bryancallahan** [comment]
Have you figured out any work arounds @kevinsimper? Take care.

**Comment by kevinsimper** [comment]
I can't remember, sorry

**Comment by goto-bus-stop** [comment]
Cleaning up old issues, please open a new one if this is still relevant.
